---
name: Bluetti to MQTT
version: 1.4.4
slug: bluetti2mqtt
description: MQTT bridge between Bluetti and Home Assistant
url: https://github.com/boy-wonder/bluetti2mqtt/commit/f4f60a23fadca14ed26b1b97d713d1d311557e45
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
usb: true
map:
  - share:rw
init: false
services:
  - mqtt:need
options:
  mqtt_username: ""
  mqtt_password: ""
  mqtt_host: ""
  mqtt_port: ""
  mode: mqtt
  ha_config: advanced
  bt_mac: 04:7F:0E:A0:2A:DA
  poll_sec: 5
  scan: false
  debug: false
schema:
  mqtt_username: str?
  mqtt_password: password?
  mqtt_host: str?
  mqtt_port: str?
  mode: list(mqtt|discovery|logger)
  ha_config: list(normal|none|advanced)
  bt_mac: match(^([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2}( ([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2})*$)
  poll_sec: int
  scan: bool
  debug: bool
